### ISSUE TITLE
Upgrading to 2.x causes error

### ISSUE THREAD

**Issue by paulalex** [dougmoscrop/serverless-plugin-log-subscription#32]
# This is a (Bug Report / Feature Proposal)

## Description

For bug reports:
* What went wrong?
```
TypeError: serverless.configSchemaHandler.defineFunctionProperties is not a function
```

* What did you expect should have happened?
The upgrade worked as expected
* What was the config you used?
`"serverless-plugin-log-subscription": "^2.0.0"`
* What stacktrace or error message from your provider did you see?
```
<html>
<body>
<!--StartFragment-->

Type Error ---------------------------------------------
--
405 |  
406 | TypeError: serverless.configSchemaHandler.defineFunctionProperties is not a function
407 | at new LogSubscriptionsPlugin (/codebuild/output/src166554412/src/node_modules/serverless-plugin-log-subscription/serverless-plugin-log-subscription.js:12:36)
408 | at PluginManager.addPlugin (/usr/local/share/.config/yarn/global/node_modules/serverless/lib/classes/PluginManager.js:94:28)
409 | at /usr/local/share/.config/yarn/global/node_modules/serverless/lib/classes/PluginManager.js:129:31
410 | at Array.forEach (<anonymous>)
411 | at PluginManager.loadAllPlugins (/usr/local/share/.config/yarn/global/node_modules/serverless/lib/classes/PluginManager.js:129:8)
412 | at /usr/local/share/.config/yarn/global/node_modules/serverless/lib/Serverless.js:88:39
413 | at tryCatcher (/usr/local/share/.config/yarn/global/node_modules/bluebird/js/release/util.js:16:23)
414 | at Promise._settlePromiseFromHandler (/usr/local/share/.config/yarn/global/node_modules/bluebird/js/release/promise.js:547:31)
415 | at Promise._settlePromise (/usr/local/share/.config/yarn/global/node_modules/bluebird/js/release/promise.js:604:18)
416 | at Promise._settlePromise0 (/usr/local/share/.config/yarn/global/node_modules/bluebird/js/release/promise.js:649:10)
417 | at Promise._settlePromises (/usr/local/share/.config/yarn/global/node_modules/bluebird/js/release/promise.js:729:18)
418 | at Promise._fulfill (/usr/local/share/.config/yarn/global/node_modules/bluebird/js/release/promise.js:673:18)
419 | at Promise._settlePromise (/usr/local/share/.config/yarn/global/node_modules/bluebird/js/release/promise.js:617:21)
420 | at Promise._settlePromise0 (/usr/local/share/.config/yarn/global/node_modules/bluebird/js/release/promise.js:649:10)
421 | at Promise._settlePromises (/usr/local/share/.config/yarn/global/node_modules/bluebird/js/release/promise.js:729:18)
422 | at Promise._fulfill (/usr/local/share/.config/yarn/global/node_modules/bluebird/js/release/promise.js:673:18)
423 | at Promise._resolveCallback (/usr/local/share/.config/yarn/global/node_modules/bluebird/js/release/promise.js:466:57)
424 | at Promise._settlePromiseFromHandler (/usr/local/share/.config/yarn/global/node_modules/bluebird/js/release/promise.js:559:17)
425 | at Promise._settlePromise (/usr/local/share/.config/yarn/global/node_modules/bluebird/js/release/promise.js:604:18)
426 | at Promise._settlePromise0 (/usr/local/share/.config/yarn/global/node_modules/bluebird/js/release/promise.js:649:10)
427 | at Promise._settlePromises (/usr/local/share/.config/yarn/global/node_modules/bluebird/js/release/promise.js:729:18)
428 | at Promise._fulfill (/usr/local/share/.config/yarn/global/node_modules/bluebird/js/release/promise.js:673:18)
429 | at PromiseArray._resolve (/usr/local/share/.config/yarn/global/node_modules/bluebird/js/release/promise_array.js:127:19)
430 | at PromiseArray._promiseFulfilled (/usr/local/share/.config/yarn/global/node_modules/bluebird/js/release/promise_array.js:145:14)
431 | at Promise._settlePromise (/usr/local/share/.config/yarn/global/node_modules/bluebird/js/release/promise.js:609:26)
432 | at Promise._settlePromise0 (/usr/local/share/.config/yarn/global/node_modules/bluebird/js/release/promise.js:649:10)
433 | at Promise._settlePromises (/usr/local/share/.config/yarn/global/node_modules/bluebird/js/release/promise.js:729:18)
434 | at Promise._fulfill (/usr/local/share/.config/yarn/global/node_modules/bluebird/js/release/promise.js:673:18)
435 | at Promise._resolveCallback (/usr/local/share/.config/yarn/global/node_modules/bluebird/js/release/promise.js:466:57)
436 | at Promise._settlePromiseFromHandler (/usr/local/share/.config/yarn/global/node_modules/bluebird/js/release/promise.js:559:17)
437 | at Promise._settlePromise (/usr/local/share/.config/yarn/global/node_modules/bluebird/js/release/promise.js:604:18)
438 | at Promise._settlePromise0 (/usr/local/share/.config/yarn/global/node_modules/bluebird/js/release/promise.js:649:10)
439 | at Promise._settlePromises (/usr/local/share/.config/yarn/global/node_modules/bluebird/js/release/promise.js:729:18)
440 | at Promise._fulfill (/usr/local/share/.config/yarn/global/node_modules/bluebird/js/release/promise.js:673:18)
441 | at PropertiesPromiseArray.PromiseArray._resolve (/usr/local/share/.config/yarn/global/node_modules/bluebird/js/release/promise_array.js:127:19)
442 | at PropertiesPromiseArray._promiseFulfilled (/usr/local/share/.config/yarn/global/node_modules/bluebird/js/release/props.js:78:14)
443 | at Promise._settlePromise (/usr/local/share/.config/yarn/global/node_modules/bluebird/js/release/promise.js:609:26)
444 | at Promise._settlePromise0 (/usr/local/share/.config/yarn/global/node_modules/bluebird/js/release/promise.js:649:10)
445 | at Promise._settlePromises (/usr/local/share/.config/yarn/global/node_modules/bluebird/js/release/promise.js:729:18)
446 | at _drainQueueStep (/usr/local/share/.config/yarn/global/node_modules/bluebird/js/release/async.js:93:12)
447 | at _drainQueue (/usr/local/share/.config/yarn/global/node_modules/bluebird/js/release/async.js:86:9)
448 | at Async._drainQueues (/usr/local/share/.config/yarn/global/node_modules/bluebird/js/release/async.js:102:5)
449 | at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/share/.config/yarn/global/node_modules/bluebird/js/release/async.js:15:14)
450 | at processImmediate (internal/timers.js:461:21)
451 |  
452 | For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

<!--EndFragment-->
</body>
</html>
```

**Comment by DJAlPee** [comment]
Duplicate? #31

**Comment by dougmoscrop** [comment]
Closing as duplicate/outdated framework issue.
