### ISSUE TITLE
 TypeError: Cannot read property 'restApi' of undefined

### ISSUE THREAD

**Issue by saskeroms** [dougmoscrop/serverless-plugin-log-subscription#38]
Hi everyone, I got the following errors apparently after deploy the version 2.1.0

 TypeError: Cannot read property 'restApi' of undefined
      at LogSubscriptionsPlugin.addApiGatewayLogSubscription (/home/ubuntu/Projects/dg-projects/dg-prs-service/service/node_modules/serverless-plugin-log-subscription/serverless-plugin-log-subscription.js:123:31)
      at LogSubscriptionsPlugin.addLogSubscriptions (/home/ubuntu/Projects/dg-projects/dg-prs-service/service/node_modules/serverless-plugin-log-subscription/serverless-plugin-log-subscription.js:43:18)
      at Object.aws:package:finalize:mergeCustomProviderResources [as hook] (/home/ubuntu/Projects/dg-projects/dg-prs-service/service/node_modules/serverless-plugin-log-subscription/serverless-plugin-log-subscription.js:10:71)
      at PluginManager.invoke (/home/ubuntu/.nvm/versions/node/v14.16.0/lib/node_modules/serverless/lib/classes/PluginManager.js:502:20)

Config:
    - enabled: true
      destinationArn: xxxxxxxx
      filterPattern: 'My Custom Pattern'

**Comment by dougmoscrop** [comment]
Try with 2.1.1 please, sorry about that

**Comment by saskeroms** [comment]
Works as expected, thank you so much.
