### ISSUE TITLE
Deploying with serverless causes a Syntax Error

### ISSUE THREAD

**Issue by spam-n-eggs** [dougmoscrop/serverless-plugin-log-subscription#39]
Versions:
- serverless@2.64.1
- serverless-plugin-log-subscription@2.0.1
- Node: v10.19.0

Stack Trace:
``` 
SyntaxError: Unexpected token .
      at Module._compile (internal/modules/cjs/loader.js:723:23)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
      at Module.load (internal/modules/cjs/loader.js:653:32)
      at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
      at Function.Module._load (internal/modules/cjs/loader.js:585:3)
      at Module.require (internal/modules/cjs/loader.js:692:17)
      at require (internal/modules/cjs/helpers.js:25:18)
      at requireServicePlugin (/var/lib/jenkins/workspace/****-common_develop/node_modules/serverless/lib/classes/PluginManager.js:34:12)
      at pluginsObject.modules.filter.map (/var/lib/jenkins/workspace/****-common_develop/node_modules/serverless/lib/classes/PluginManager.js:181:22)
      at Array.map (<anonymous>)
      at PluginManager.resolveServicePlugins (/var/lib/jenkins/workspace/****-common_develop/node_modules/serverless/lib/classes/PluginManager.js:178:10)
      at PluginManager.loadAllPlugins (/var/lib/jenkins/workspace/****-common_develop/node_modules/serverless/lib/classes/PluginManager.js:161:10)
      at Serverless.init (/var/lib/jenkins/workspace/****-common_develop/node_modules/serverless/lib/Serverless.js:213:30)
```

**Comment by beanaroo** [comment]
Can confirm the same error on:
- serverless@2.69.1
- serverless-plugin-log-subscription@2.1.1
- Node: v12.22.7

```
$ sls package --package serverless
 
 Syntax Error --------------------------------------------
 
  /home/mike/Documents/Clubware/src/microservices/reporting-service/node_modules/serverless-plugin-log-subscription/serverless-plugin-log-subscription.js:299
      return res?.Stacks.length > 0;
                 ^
  
  SyntaxError: Unexpected token '.'
      at wrapSafe (internal/modules/cjs/loader.js:915:16)
      at Module._compile (internal/modules/cjs/loader.js:963:27)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
      at Module.load (internal/modules/cjs/loader.js:863:32)
      at Function.Module._load (internal/modules/cjs/loader.js:708:14)
      at Module.require (internal/modules/cjs/loader.js:887:19)
      at require (internal/modules/cjs/helpers.js:74:18)
      at requireServicePlugin (/home/mike/Documents/Clubware/src/microservices/reporting-service/node_modules/serverless/lib/classes/PluginManager.js:34:12)
      at /home/mike/Documents/Clubware/src/microservices/reporting-service/node_modules/serverless/lib/classes/PluginManager.js:181:22
      at Array.map (<anonymous>)
      at PluginManager.resolveServicePlugins (/home/mike/Documents/Clubware/src/microservices/reporting-service/node_modules/serverless/lib/classes/PluginManager.js:178:10)
      at PluginManager.loadAllPlugins (/home/mike/Documents/Clubware/src/microservices/reporting-service/node_modules/serverless/lib/classes/PluginManager.js:161:10)
      at Serverless.init (/home/mike/Documents/Clubware/src/microservices/reporting-service/node_modules/serverless/lib/Serverless.js:213:30)
      at async /home/mike/Documents/Clubware/src/microservices/reporting-service/node_modules/serverless/scripts/serverless.js:585:7
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
```

**Comment by spam-n-eggs** [comment]
@beanaroo For what it's worth, I took some time to upgrade our build server to NodeJS 16.13.1 and it seems to be working with that particular version of Node.  If I were a betting man, I would bet that it would work with 14.18.2, but I don't want to go through that testing now that we're stable.  The problem is that 12.22.8 is still also in LTS maintenance mode, so it _should_ be backward compatible, or have the packages.json updated to only reflect the versions of node that are supported.

**Comment by beanaroo** [comment]
Thanks @spam-n-eggs. We have plans to upgrade Node next year but it will be a while.

We have pinned this plugin to v2.0.1 for the time being.

https://github.com/dougmoscrop/serverless-plugin-log-subscription/compare/v2.0.1...v2.1.0#diff-caea53424c462e8e63aca02ddd113589d05cf1022af329ff2f21a43ac4dd8a12R299

**Comment by tedsmitt** [comment]
@beanaroo I've submitted [Remove optional chaining for backward compatibility with Node 12 #41](https://github.com/dougmoscrop/serverless-plugin-log-subscription/pull/41) to fix this. Happy for the plugin to remain pinned to 2.0.1.
